apiVersion: 1
groups:
    - orgId: 1
      name: Alert
      folder: Rules
      interval: 10s
      rules:
        - uid: fe5ewkanug0e8b
          title: SQL Injection Attempts
          condition: C
          data:
            - refId: A
              queryType: range
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: de5e0bnmz7r40a
              model:
                datasource:
                    type: loki
                    uid: de5e0bnmz7r40a
                editorMode: code
                expr: count_over_time({job="mysql_audit"} |= "' OR"[1m])
                intervalMs: 1000
                legendFormat: SQL Injection Attempts
                maxDataPoints: 43200
                queryType: range
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 10
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
          dashboardUid: ae5easyzntb0gb
          panelId: 2
          noDataState: OK
          execErrState: Error
          for: 10s
          annotations:
            __dashboardUid__: ae5easyzntb0gb
            __panelId__: "2"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Test
